# Uses https://github.com/firebelley/godot-export
# Based on the example at
# https://github.com/firebelley/godot-export/blob/c33022506d60b68b8b5f5156339a1412d92e0479/README.md#using-tag-as-base_version
# Copyright 2020 Outfrost
# This work is free. It comes without any warranty, to the extent
# permitted by applicable law. You can redistribute it and/or modify it under
# the terms of the Do What The Fuck You Want To Public License, Version 2,
# as published by Sam Hocevar. See the LICENSE.WTFPL file for more details.

name: Build and release

on:
  push:
    tags:
      - 'v[0-9]+.*'

jobs:
  export_release_project:
    # Always use ubuntu-latest for this action
    runs-on: ubuntu-latest
    name: Export and release project
    steps:

    - name: Checkout
      uses: actions/checkout@v2.3.1
      # Ensure that we get the entire project history
      with:
        fetch-depth: 0

      # Job creates release under the same version as the tag
    - name: Get version from tag
      id: tag_version
      run: |
        echo ::set-output name=TAG_VERSION::${GITHUB_REF#refs/tags/v}

    - name: Export and release
      uses: firebelley/godot-export@v2.4.0
      with:
        godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/3.2.2/Godot_v3.2.2-stable_linux_headless.64.zip
        godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/3.2.2/Godot_v3.2.2-stable_export_templates.tpz
        relative_project_path: ./
        create_release: true
        generate_release_notes: true
        base_version: ${{ steps.tag_version.outputs.TAG_VERSION }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
